# OSV-Scanner ignore file
# This file contains vulnerabilities to ignore from OSV-Scanner
# https://google.github.io/osv-scanner/configuration/

# Vulnerabilities from static website generator (Docusaurus)
# These are development dependencies and not part of the production build
IgnoredVulns:
  - id: GHSA-76c9-3jph-rj3q
    reason: Static website generator - not in production code
  - id: GHSA-4v9v-hfq4-rm2v
    reason: Static website generator - not in production code  
  - id: GHSA-9jgg-88mc-972h
    reason: Static website generator - not in production code
  - id: GO-2024-2920
    reason: Static website generator - not in production code
  - id: GHSA-2hmf-46v7-v6fx
    reason: Static website generator - not in production code