// Code generated by cmd/gen-source-variants. DO NOT EDIT.

package dalec

import (
	"fmt"
)

// validateSourceVariants ensures exactly one source variant is set
func (s *Source) validateSourceVariants() error {
	count := 0

	if s.Build != nil {
		count++
	}
	if s.Context != nil {
		count++
	}
	if s.DockerImage != nil {
		count++
	}
	if s.Git != nil {
		count++
	}
	if s.HTTP != nil {
		count++
	}
	if s.Inline != nil {
		count++
	}

	switch count {
	case 0:
		return fmt.Errorf("no non-nil source variant")
	case 1:
		return nil
	default:
		return fmt.Errorf("more than one source variant defined")
	}
}

// toInterface returns the underlying source interface implementation
func (s *Source) toInterface() source {
	switch {
	case s.Build != nil:
		return s.Build
	case s.Context != nil:
		return s.Context
	case s.DockerImage != nil:
		return s.DockerImage
	case s.Git != nil:
		return s.Git
	case s.HTTP != nil:
		return s.HTTP
	case s.Inline != nil:
		return s.Inline
	default:
		panic(errNoSourceVariant)
	}
}
