package rpm

import (
	"bytes"
	"fmt"
	"path/filepath"
	"runtime/debug"

	"github.com/moby/buildkit/client/llb"
	"github.com/project-dalec/dalec"
)

func RPMSpec(spec *dalec.Spec, in llb.State, targetKey, dir string, opts ...llb.ConstraintsOpt) llb.State {
	return RPMSpecWithSourceFilter(spec, in, targetKey, dir, dalec.SourceFilterConfig{}, opts...)
}

func RPMSpecWithSourceFilter(spec *dalec.Spec, in llb.State, targetKey, dir string, filter dalec.SourceFilterConfig, opts ...llb.ConstraintsOpt) llb.State {
	if err := ValidateSpec(spec); err != nil {
		return dalec.ErrorState(llb.Scratch(), fmt.Errorf("invalid spec: %w", err))
	}
	opts = append(opts, dalec.ProgressGroup("Generate RPM spec"))
	buf := bytes.NewBuffer(nil)
	info, _ := debug.ReadBuildInfo()
	buf.WriteString("# Automatically generated by " + info.Main.Path + "\n")
	buf.WriteString("\n")

	if err := WriteSpecWithSourceFilter(spec, targetKey, filter, buf); err != nil {
		return dalec.ErrorState(llb.Scratch(), err)
	}

	if dir == "" {
		dir = "SPECS/" + spec.Name
	}

	return in.
		File(llb.Mkdir(dir, 0755, llb.WithParents(true)), opts...).
		File(llb.Mkfile(filepath.Join(dir, spec.Name)+".spec", 0640, buf.Bytes()), opts...)
}

func BuildRoot(worker llb.State, spec *dalec.Spec, sOpt dalec.SourceOpts, targetKey string, opts ...llb.ConstraintsOpt) llb.State {
	opts = append(opts, dalec.ProgressGroup("Create RPM buildroot"))
	sources := Sources(worker, spec, sOpt, opts...)
	filter, err := sOpt.GetSourceFilter()
	if err != nil {
		return dalec.ErrorState(llb.Scratch(), err)
	}
	return RPMSpecWithSourceFilter(spec, dalec.MergeAtPath(llb.Scratch(), sources, "SOURCES", opts...), targetKey, "", filter, opts...)
}
