name: deploy-docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'website/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'website/**'

permissions:
  contents: read

jobs:
  deploy:
    name: Generate docs website to GitHub Pages
    runs-on: ubuntu-latest
    environment: deploy-docs
    permissions:
      contents: write
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            ghcr.io:443
            github.com:443
            *.githubusercontent.com:443
            *.blob.core.windows.net:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443
            cdn.jsdelivr.net:443

      - name: Build Hugo image
        run: docker build --tag dalec-hugo .

      - name: Build website
        run: >-
          docker run --rm
          --volume "$PWD:/project"
          --workdir /project
          --entrypoint hugo
          dalec-hugo
          --gc
          --minify

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push' && github.repository == 'project-dalec/dalec'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          destination_dir: ./docs
