name: Release

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'

permissions:
  contents: read
  packages: write

jobs:
  trimTagRef:
    runs-on: ubuntu-latest
    outputs:
      TRIMMED_REF_NAME: ${{ steps.trim.outputs.TRIMMED_REF_NAME }}
    steps:
      - name: Trim tag ref
        id: trim
        run: echo "TRIMMED_REF_NAME=${REF_NAME#v}" >> "$GITHUB_OUTPUT" && cat "$GITHUB_OUTPUT"
        env:
          REF_NAME: ${{ github.ref_name }}

  build:
    needs: trimTagRef
    uses: ./.github/workflows/frontend-image.yml
    with:
      tag: ${{needs.trimTagRef.outputs.TRIMMED_REF_NAME}}