name: Release

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'

permissions:
  contents: read

jobs:
  tagList:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.OUTPUT_TAGS }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Get image tag list
        id: tags
        run: |
          set -eux -o pipefail

          # Remove leading "v" from tag name
          TRIMMED_REF_NAME="${REF_NAME#v}"

          # Creates a comma separated list of tags
          # - latest
          # - <major>.<minor>
          # - <major>.<minor>.<patch>
          OUTPUT_TAGS="latest,${TRIMMED_REF_NAME%.*},${TRIMMED_REF_NAME}"
          
          echo "OUTPUT_TAGS=${OUTPUT_TAGS}" >> "$GITHUB_OUTPUT" && cat "$GITHUB_OUTPUT"
        env:
          REF_NAME: ${{ github.ref_name }}
        shell: bash

  build:
    permissions:
      packages: write

    needs: tagList
    uses: ./.github/workflows/frontend-image.yml
    with:
      tag: ${{needs.tagList.outputs.tags}}
