name: Publish toolkit image to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true
        default: 'latest'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/build-image
        with:
          repo: mariner2/toolchain
          tag: ${{ github.event.inputs.tag }}
          target: toolchain
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: frontend/mariner2/Dockerfile
 