name: Publish toolkit image to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true
        default: 'latest'
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: docker/login-action@v2
        name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker buildx create --use

          export TAG_REF="$(tr '[:upper:]' '[:lower:]' <<<"${TAG_REF}")"
          export CACHE_REF="$(tr '[:upper:]' '[:lower:]' <<<"${CACHE_REF}")"

          # For the toolchain we'll provide a separate cache image with a known tag
          # This makes it easier when making changes to the toolchain image to have a easily targetable cache ref.
          cache="type=registry,ref=${CACHE_REF}"
          docker buildx bake --push \
            --set mariner2-toolchain.tags=${TAG_REF} \
            --set mariner2-toolchain.cache-to=${cache} \
            --set mariner2-toolchain.cache-from=${cache} \
            mariner2-toolchain
        env:
          TAG_REF: ghcr.io/${{ github.repository }}/mariner2/toolchain:${{ github.event.inputs.tag }}
          CACHE_REF: ghcr.io/${{ github.repository }}/mariner2/toolchain:cache
