name: Build Worker Images

on:
  push:
    branches:
      - main
      - 'releases/*'
    tags:
      - 'v[0-9]+.[0-9]+.*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/worker-images/matrix.json'
      - '.github/workflows/worker-images.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  load-matrix:
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses:  actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set matrix
        id: set-matrix
        run: |
          MATRIX=$(cat .github/workflows/worker-images/matrix.json)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build-worker-images:
    permissions:
      packages: write
    needs: load-matrix
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.load-matrix.outputs.matrix) }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/enable-containerd
      - uses: ./.github/actions/setup-source-policy
        name: Setup Source Policy
        id: source-policy
      - name: Setup environment
        run: |
          echo MAIN_CACHE_SCOPE=main.${{ matrix.target }} >> $GITHUB_ENV

          tag="${{ github.ref_name }}"
          tag="${tag//\//-}" # Replace slashes with dashes
          tag="${tag%.*}" # Trim off patch version if it exists

          BASE_REPO="${{ steps.source-policy.outputs.formatted-repo }}/${{ matrix.target }}"
          echo "BASE_REPO=${BASE_REPO}" >> $GITHUB_ENV
          echo "IMAGE_REPO=${BASE_REPO}:${tag}" >> $GITHUB_ENV
      - if: ${{ github.event_name == 'pull_request' }}
        name: Setup up (PR)
        run: |
          set -eux
          # Here we try to build this as much like a release as possible, but we push to a local registry

          ref="localhost:5000/${IMAGE_REPO}"
          EXTRA_FLAGS="--set worker.cache-from=type=gha,scope=${MAIN_CACHE_SCOPE} --set worker.tags=${ref} --push"

          # Because we sometimes add an extra ref for ":latest", let's also do that here to validate that it works
          EXTRA_FLAGS+=" --set worker.tags=${ref}-latest"

          echo "EXTRA_FLAGS=${EXTRA_FLAGS}" >> $GITHUB_ENV

          docker run -d --net=host ghcr.io/${{ steps.source-policy.outputs.formatted-repo }}/mirror/dockerhub/library/registry:latest
      - if: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || github.event_name == 'workflow_dispatch' }}
        name: Setup (tagged)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -eux

          ref="ghcr.io/${IMAGE_REPO}"

   
          # Don't need o care about cache-from in this case as this is the "prod" image, better to build it from scratch
          # Inline the cache with the image so others can use it as a cache-from for their own builds.
          EXTRA_FLAGS="--set worker.cache-to=type=inline,mode=max --set worker.tags=${ref} --push"

          latest="$(gh release view --json tagName -q .tagName)"
          if [ ${{ github.ref_name }} = "${latest}" ]; then
            # If this is the latest release, we also tag it as "latest"
            IMAGE_REPO_LATEST="${BASE_REPO}:latest"
            EXTRA_FLAGS+=" --set worker.tags=ghcr.io/${IMAGE_REPO_LATEST}"
          fi

          echo "EXTRA_FLAGS=${EXTRA_FLAGS}" >> $GITHUB_ENV
      - if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
        name: Setup (merged)
        run: |
          set -ex -o pipefail
          EXTRA_FLAGS="--set worker.cache-to=type=gha,scope=main.${{matrix.target}},mode=max --set worker.cache-from=type=gha,scope=${MAIN_CACHE_SCOPE}"
          echo "EXTRA_FLAGS=${EXTRA_FLAGS}" >> $GITHUB_ENV
      - name: Setup QEMU
        run: docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - name: Expose GitHub tokens for caching
        uses: crazy-max/ghaction-github-runtime@3cb05d89e1f492524af3d41a1c98c83bc3025124 # v3.1.0
      - name: Build worker images
        run: |
          set -eux

          docker buildx bake worker \
            --set worker.platform=linux/amd64,linux/arm64 \
            ${EXTRA_FLAGS}
        env:
          WORKER_TARGET: ${{ matrix.target }}
